### ISSUE TITLE
wpa parameters missing from network::interface

### ISSUE THREAD

**Issue by fnoop** [example42/puppet-network#105]
Various wpa parameters can be set in debian /etc/network/interfaces interface definition and should be supported by network::interface.   At the very least:
 wpa-ssid
 wpa-psk

**Comment by hessijames79** [comment]
Agreed. Please also add:
wireless-power

**Comment by alvagante** [comment]
can you provide a relevant PR? follow the approach used in similar cases, possibly puppet-linting the code

**Comment by fnoop** [comment]
Thanks wpa parameters working now :) . @hessijames79 I think wireless options are a different matter, as they are mapped to iwconfig options apparently.  Will open a separate issue for that.
