### ISSUE TITLE
Can't set bond option num_grat_arp on Debian

### ISSUE THREAD

**Issue by ddryden** [example42/puppet-network#112]
## Expected Behavior 
I'd like to be able to configure the bond option num_grat_arp for bond interfaces on Debian derived systems(RedHat and Suse in the same way you can currently specify values for mode, miimon, updelay etc.

Everything else seems to be working on Debian Jessie though.

## Actual Behavior
It's an unknown network::interface parameter.

## Steps to Reproduce the Problem

Define a bond interface with like this in hiera and deploy to Debian:
```network::interfaces_hash:
'bond0':
  method: 'manual'
  bond_mode: 'active-backup'
  bond_miimon: '100'
  bond_downdelay: '200'
  bond_updelay: '200'
  bond_num_grat_arp: '5'
  bond_primary: 'eth0'
  bond_slaves: ['eth0','eth1']
```

## Specifications

Please add this info:
  1. Version of Puppet and of the module
OS: Debian Jessie
Puppet version: 3.7.2
Module version: example42/puppet_network branch master on 12th May 2016
  1. The relevant Puppet code and eventually Hiera data
See above.

**Comment by alvagante** [comment]
Fixed in pr #113  ty
