### ISSUE TITLE
bonding_master paramter missing on RedHat

### ISSUE THREAD

**Issue by stdietrich** [example42/puppet-network#117]
Hi,

in the current version of this module, the BONDING_MASTER parameter is not available.
This paramter is required in order to setup a proper channel bond on RedHat.
The value can be either 'yes' or 'no' and it has to be configured in the configuration file for the main bond device.
This is also mentioned in the [RedHat documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Network_Bonding_Using_the_Command_Line_Interface.html#sec-Create_a_Channel_Bonding_Interface)

Regards,
Stefan

**Comment by alvagante** [comment]
Can you confirm me that the proposed fix is enough?

**Comment by stdietrich** [comment]
Yes, this is enough.
I already did the same in our forked version with a basic sanity check and tested it, see desyops/puppet-network@af8d4155ae510f74c4eb5e946b1369ce95a0dee8.
With that little change, the bonded interface is properly configured and usable.
In the end, I just forgot to create the PR :(

**Comment by alvagante** [comment]
merged
