### ISSUE TITLE
use_carrier and primary_reselect parameters missing under bonding

### ISSUE THREAD

**Issue by b-0-b** [example42/puppet-network#119]
## Expected Behavior 
Abel to control use_carrier and primary_reselect parameters on Debian through puppet

## Actual Behavior
Setting use_carrier or primary_reselect in the interfaces_hash in hiera causes the puppet run to fail.

## Steps to Reproduce the Problem

  1. set use_carrier or primary_reselect in hiera on Debian
  2. Do puppet agent -vt 

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
os => {
  architecture => "amd64",
  distro => {
    codename => "jessie",
    description => "Debian GNU/Linux 8.2 (jessie)",
    id => "Debian",
    release => {
      full => "8.2",
      major => "8",
      minor => "2"
    }
  },

  1. Version of Puppet and of the module
/root # puppet agent --version
4.3.1

  1. The relevant Puppet code and eventually Hiera data
Puppet
...
  if hiera('network::interfaces_hash', undef) {
    include network
  }
...

Hiera
...
network::interfaces_hash:
  "bond0":
    bond_mode: "active-backup"
    bond_miimon: "100"
    bond_num_grat_arp: "10"
    bond_downdelay: "200"
    bond_updelay: "200"
    bond_primary: "eth0"
    bond_slaves:
      - eth0
      - eth1
    use_carrier: "1"
    primary_reselect: "better"
  "vlan255":
    address: "10.0.255.38"
    netmask: '255.255.255.0'
    network: "10.0.255.0"
    broadcast: "10.0.255.255"
    gateway: "10.0.255.250"
    dns_nameservers: "127.0.0.1"
    dns_search:
      - foo.bar
    vlan_raw_device: 'bond0'
...

**Comment by alvagante** [comment]
merged your pr, thanks
