### ISSUE TITLE
IP route with specific dev and gw/via

### ISSUE THREAD

**Issue by skorpy2009** [example42/puppet-network#121]
puppet-network/templates/mroute_up-Debian.erb
## Expected Behavior

ip route add **\* dev **\* via ***
## Actual Behavior

ip route add <%= net %> <% if /^\d/.match(gw) %>via<% else %>dev<% end %> <%= gw %>

The else structure and not double if makes it not possible to define trough what device the traffic will go in case of a gateway is defined.

**Comment by alvagante** [comment]
Is that really necessary? I expect that given a gw ip the relevant device to use can only be the direclty connected one.

**Comment by alvagante** [comment]
A possible workaround is to use the new route_up_template and route_down_template parameters of network::mroute (see referenced commit)
