### ISSUE TITLE
BRIDGE_PORTS on OpenSUSE not handled as array

### ISSUE THREAD

**Issue by MrManor** [example42/puppet-network#122]
## Expected Behavior 
When no BRIDGE_PORTS is specified /etc/sysconfig/network/ifcfg-[whatever] should contain
BRIDGE_PORTS=""

## Actual Behavior
BRIDGE_PORTS="[]"

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
Fails on all my suse based units. 

  1. Version of Puppet and of the module
Module version 3.3.2

  1. The relevant Puppet code and eventually Hiera data
  network::routes_hash:
    'default':
      destination: default
      gateway:     130.225.200.1
  network::interfaces_hash:
    'ens160':     
      bootproto: static
      ipaddress: 130.225.200.3
      netmask: 255.255.255.0

**Comment by alvagante** [comment]
Please let me know if the above commit is ok.

**Comment by MrManor** [comment]
Works for me. Thanks!
