### ISSUE TITLE
Allow overloading of loopback

### ISSUE THREAD

**Issue by AlexSamad** [example42/puppet-network#124]
I can add config for lo:1 but it is of type ethernet
## Steps to Reproduce the Problem
1. 
2. 
3. 
## Specifications

Please add this info:
1. Output of `facter -p` on the failing node (at least the OS related facts)
2. Version of Puppet and of the module
3. The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
network::interface has the 'type' parameter which can define the interface type (default is 'Ethernet')
