### ISSUE TITLE
enhancement: Support for single interface config files on Cumulus Linux

### ISSUE THREAD

**Issue by TorLdre** [example42/puppet-network#128]
## Expected Behavior

When enabling $network::config_file_per_interface for debian platform, the module should create working interface files for Cumulus Linux (based on debian).
## Actual Behavior

Cumulus Linux will not start interfaces with .cfg postfix, and will not execute addon scripts like route scripts
## Steps to Reproduce the Problem
1. On cumulus linux, create interface with module
2. Optionally, create an addon script
3. run service networking restart
4. Observe Cumulus Linux ignore the configured files
## Specifications

Please add this info:
1. Output of `facter -p` on the failing node (at least the OS related facts)
   operatingsystem => CumulusLinux
   operatingsystemmajrelease => 2
   operatingsystemrelease => 2.5.10
   puppetversion => 3.6.2
1. Version of Puppet and of the module
   Puppet 3.6.2
   "name": "example42-network",
   "version": "3.3.1",
   1. The relevant Puppet code and eventually Hiera data
      Fix we use locally:
      https://github.com/norcams/puppet-network/commit/0529e7b415c0fc0a2d6d718301af05aec0422632

**Comment by TorLdre** [comment]
The rationale behind this change is that, while Cumulus Networks provides their own puppet modules for configuring the switch ports, the management interface can't be configured with their modules if you choose to use a management VRF (which is recommended). So, we use this module that provides custom routing tables etc for the management interface.

**Comment by TorLdre** [comment]
@alvagante Do You think I can create a pull request for this one?

**Comment by alvagante** [comment]
@TorLdre yes definitively ty

**Comment by alvagante** [comment]
@TorLdre FYI, I've just pushed this: https://github.com/example42/control-repo/commit/ec5806b1fb4092af12f80a33a5e319c298ba1e4b
to allow Puppet4 installation on Cumulus Linux  (tested in the official Vagrant box).
You might find it useful:

    wget -O - https://bit.ly/installpuppet | sudo bash

**Comment by TorLdre** [comment]
I'll definitely look into it! We're still at puppet 3, but that cannot
last, of course.

2017-01-09 14:18 GMT+01:00 Alessandro Franceschi <notifications@github.com>:

**Comment by alvagante** [comment]
@TorLdre BTW on what versions of Cumulus your patch should work?
I placed here the 3.0.0, 3.1.0 and 3.2.0 versions, but maybe that's not a correct info
https://github.com/example42/puppet-network/blob/master/metadata.json

**Comment by TorLdre** [comment]
@alvagante As stated in the PR, We use this for Cumulus Linux 2.5.x, but should work for 3.x too, as I can't see that config of interfaces has changed from 2.5 to 3. If you want to, I can spin up a 3.x VM and test?

**Comment by alvagante** [comment]
@TorLdre only when and if you have time, thank you

**Comment by TorLdre** [comment]
@alvagante I'll write it to my todo-list.

**Comment by TorLdre** [comment]
@alvagante Anyway, you could add 2.5.x to supported releases?

**Comment by alvagante** [comment]
ok, just done
