### ISSUE TITLE
SLES 12 Support

### ISSUE THREAD

**Issue by Klaas-** [example42/puppet-network#129]
I would like to use this module with sles 12. I'll open a PR with the changes needed for this. I'll also change the behaviour that sles gets treated differently than other operating systems when using real_routes_hash.

**Comment by alvagante** [comment]
Are the changes in the PR working also on Suse11?

**Comment by Klaas-** [comment]
@alvagante I'm not sure I only have suse 12 atm; but I read the documentation and the ifroute files should be supported the same way sles12 uses them (https://www.suse.com/documentation/sled11/book_sle_admin/data/sec_basicnet_manconf.html).

I changed the logic to be equal to the redhat/debian routes. this may be a breaking change because the old suse template was handling things a little different (gateway is not a required field anymore, but netmask needs to be supplied which was not the case in old template, type is no keyword anymore - options get handled like with rhel/debian)

the ifrule files won't work on any sles as of right now -- the change is already in upstream wicked though; should be included in one of the next releases

**Comment by alvagante** [comment]
Ok, pls give me some time for testing before merging (I'm at the Puppetconf now, not so much time available... )
