### ISSUE TITLE
Network Mask is wrong when using more IP Adresses on one Interface under RedHat 

### ISSUE THREAD

**Issue by RockoPB** [example42/puppet-network#141]
## Expected Behavior 
/etc/sysconfig/network-scripts/eth0
IPADDR1="10.0.0.1"
IPADDR2="10.0.0.2"
NETMASK1="255.255.255.0"
NETMASK2="255.255.255.0"

## Actual Behavior
/etc/sysconfig/network-scripts/eth0
IPADDR1="10.0.0.1"
IPADDR2="10.0.0.2"
NETMASK="255.255.255.0"

## Steps to Reproduce the Problem

  1. Configure Network Interface with two ip addresses
  network::interface { 'eth0':
    ipaddress       => ['10.0.0.1','10.0.0.2'],
    netmask         => '255.255.255.0',
    bootproto       => 'static',
    gateway         => $standard_gw,
    dns1            => $dns_server_1,
    dns2            => $dns_server_2,
    domain          => $dns_domain,
  }

 2. it did not work when using network mask as an array neither

## Specifications

Please add this info:
Version: mod 'example42-network', '3.3.5'

**Comment by alvagante** [comment]
Thank for the PR, merged
