### ISSUE TITLE
Multiple ipaddresses per interface breaks on Debian/Ubuntu

### ISSUE THREAD

**Issue by thardie** [example42/puppet-network#145]
## Expected Behavior 
Interfaces file should contain:
`auto eth0`
`iface eth0 inet static`
`    address 10.0.0.1/24`

`iface eth0 inet static`
`    address 10.0.0.2/24`
From config:
`network::interface { 'eth0':`
`  ipaddress => [ '10.0.0.1/24', '10.0.0.2/24' ]`
`}`
The array support was added recently for RedHat to support multiple IPs, but doesn't work on Debian/Ubuntu

## Actual Behavior
Interfaces file gets:
`auto eth0`
`iface eth0 inet static`
`    address 10.0.0.1/2410.0.0.2/24`

## Steps to Reproduce the Problem

  1. Set IP address to an array instead of a single IP

## Specifications
Interfaces file for multiple IPs should be according to:
[https://wiki.debian.org/NetworkConfiguration#Multiple_IP_addresses_on_one_Interface](url)

**Comment by alvagante** [comment]
In order to manage multiple ip addresses on the same interface you can still use interfaces aliases, which are supported by the module.
