### ISSUE TITLE
How do I create a default route on RedHat system?

### ISSUE THREAD

**Issue by redcricket** [example42/puppet-network#146]
## Expected Behavior 
On RHEL7.2 host and given puppet code of:

```
    network::route { 'eth0':
        ipaddress => ["default"        , "$this_hosts_eth0_ip"   ],
        netmask   => [ false           , "${eth0_prefix}"],
        gateway   => ["${eth0_gateway}", false],
        table     => ["table1"         , "table1"],
    } 
```
produce /etc/sysconfig/network-scripts/route-eth0 that contains:

```
default via 10.199.12.193 dev eth0 table 1
10.199.2.66/27 dev eth0 table 1

```

## Actual Behavior

route-eth0 file contains:

```
 ###
 ### File managed by Puppet
 ###
default/false via 10.199.12.193 dev eth0 table table1
10.199.2.66/27 dev eth0 table table1

``` 

## Steps to Reproduce the Problem

  1. use the puppet described above
  1. run puppet agent -t on node

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)

# facter -p interfaces
eth0,eth1,lo

  1. Version of Puppet and of the module

puppet -V
4.5.2

example42-network (v3.3.5)

  1. The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
Try to change:
        netmask   => [ false           , "${eth0_prefix}"],
with:
        netmask   => [ '0'           , "${eth0_prefix}"],


Note also tha in order to manage multiple routes, it's probably better to use the mroute define.

**Comment by redcricket** [comment]
Thanks alvagant!
Can I use mroute to generate route-eth0 file like this?

# cat /etc/sysconfig/network-scripts/route-eth0 
10.199.12.192/27 dev eth0 table 1
default via 10.199.12.193 dev eth0 table 1

I need the "table 1" bit in there.  I can't see how I would use mroute to do that.

**Comment by alvagante** [comment]
Oops, currently mroute does not support tables. 
It should not be a greet problem to add them, in a retrocompatible way.
Wanna try with a PR?

**Comment by redcricket** [comment]
PR means pull request?

**Comment by alvagante** [comment]
Yes

**Comment by alvagante** [comment]
Even if not much elegant you can actually on network::mroute  add the table in the table reference directly in the routes values:

network::mroutes_hash:
  eth0:
    routes:
      10.199.12.192/27: 'eth0 table 1'
