### ISSUE TITLE
Incorrect IPV6 Format for Redhat Based Distros

### ISSUE THREAD

**Issue by HW-Peter** [example42/puppet-network#159]
## Expected Behavior 

IPv6 Address Correctly Binds to Server

## Actual Behavior

IPv6 Address does not bind to server, instead we are given an obscure error about being unable to add a default route

## Steps to Reproduce the Problem

  1. Setup a network interface with an IPv6 Address
  2. Restart Networking
  3. Check the ips bound and you will see the ip was not bound

**Comment by alvagante** [comment]
merged pr
