### ISSUE TITLE
wireless options missing

### ISSUE THREAD

**Issue by fnoop** [example42/puppet-network#161]
As referenced in: https://github.com/example42/puppet-network/issues/105

wireless-* options should be available, as they are crucial for setting up some wireless configurations.  I believe these are mapped to iwconfig options, so maybe need to be handled programmatically, if that is possible?

**Comment by alvagante** [comment]
What exactly has to be done here?
If it's a matter of adding new options to the interface file, then this is straightforward (new param added to network::interface and to the relevant template, as, for example, here: https://github.com/example42/puppet-network/pull/154/files).
PR welcomed.

**Comment by fnoop** [comment]
@alvagante I'm sorry I don't know the best way to do this.  I just want wireless-mode option, but there are many other wireless- options that correspond to iwconfig options.  I don't know if there's a way in puppet to have 'dynamic' parameters, so the interface manifest could accept any parameter that starts with wireless-, or if they all have to be manually specified.

**Comment by alvagante** [comment]
Dynamic parameters are not possible, but network::interface has already an options parameter, which expects an hash of key-values which may be used in a custom template (configurable via the template parameter).
So, it's already possible with the current code, to have custom wireless (or whatever) options, but if we want to have them explicitly set, we need to add them all, both in the network::interface define's parameters and in the relevant templates

**Comment by fnoop** [comment]
Aha!  Yes template and options are very flexible and allow you to add whatever you want.  Great, thanks :)
