### ISSUE TITLE
Enhancement: It should be possible to configure port configuration for team members

### ISSUE THREAD

**Issue by TorLdre** [example42/puppet-network#165]
## Expected Behavior 
When configuring members for a network team on RedHat based systems, you want to configure TEAM_PORT_CONFIG for each individual member, for example port priority, ie { "prio" : 100 }

## Actual Behavior
No option for this is provided in module

## Specifications
I can provide a PR with the necessary option for interfaces.pp and RedHat.erb

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
  1. Version of Puppet and of the module
  1. The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
PR welcomed.

**Comment by TorLdre** [comment]
I opened a new PR to fix one line in the template that was forgotten when renaming parameter.

**Comment by llexus** [comment]
Hello, found it working with the following:
Replace
<% if @team_port_cfg -%>
by
<% if @team_port_config -%>
in templates/interface/RedHat.erb:129

**Comment by alvagante** [comment]
The change is on upstream git repo. Not yet published to the forge, will do that soon.
