### ISSUE TITLE
Multiple IPs on RedHat breaks default gateway

### ISSUE THREAD

**Issue by ctrox** [example42/puppet-network#176]
## Expected Behavior 
```
network::interface { 'eth0':
  ipaddress => ['1.2.3.4', '1.2.3.5'],
  netmask   => '255.255.255.0',
  gateway   => '1.2.3.1',
}
```
This should create a interface with multiple IP addresses and a default gateway '1.2.3.1'.
## Actual Behavior
This creates a config like this:
```
IPADDR1="1.2.3.4" 
IPADDR2="1.2.3.5" 
NETMASK1="255.255.255.0" 
NETMASK2="255.255.255.0" 
GATEWAY="1.2.3.1" 
```
As there is no `IPADDR` (without a number) the `GATEWAY` does not seem to work properly. The route looks like this `1.2.3.1 dev eth0 proto static metric 100` but it should be `default via 1.2.3.1 dev eth0 proto static metric 100`. Setting `DEFROUTE=yes` does not have an impact on this.

One way to fix this would be to set the gateway using `GATEWAY1` as soon as there's multiple IP addresses. I'm not sure if there's other ways but I can submit a PR if you like.

## Steps to Reproduce the Problem

  1. Create an interface as noted above
  2. Check routes for a default gateway with the command `ip route`

## Specifications

```
operatingsystem => RedHat
operatingsystemmajrelease => 7
operatingsystemrelease => 7.4

puppet -V
3.8.7

example42-network (v3.3.7)
```

**Comment by alvagante** [comment]
Hi, if having a line with GATEWAY1 works , when multiple ips are present, then it's ok for me. PR welcomed.

**Comment by mihall-primus** [comment]
This seems to break on at least CentOS 7.6.1810.

For example:

  network::interface { 'ens192':
    ipaddress => [
      '10.61.130.68',
      '10.61.130.69',
      '10.61.130.70',
    ],
    netmask   => '255.255.254.0',
    gateway   => '10.61.131.254',
  }

results in:

# File Managed by Puppet
DEVICE="ens192"
BOOTPROTO="none"
ONBOOT="yes"
TYPE="Ethernet"
USERCTL="no"
PEERDNS="no"
PEERNTP="no"
IPADDR1="10.61.130.68"
IPADDR2="10.61.130.69"
IPADDR3="10.61.130.70"
NETMASK1="255.255.254.0"
NETMASK2="255.255.254.0"
NETMASK3="255.255.254.0"
GATEWAY1="10.61.131.254"

However, no gateway gets configured:

$ /sbin/ip route show
10.61.130.0/23 dev ens192 proto kernel scope link src 10.61.130.68
169.254.0.0/16 dev ens192 scope link metric 1003

If I change GATEWAY1 to GATEWAY, and restart networking, the default gateway is set:

$ /sbin/ip route show
default via 10.61.131.254 dev ens192
10.61.130.0/23 dev ens192 proto kernel scope link src 10.61.130.68
169.254.0.0/16 dev ens192 scope link metric 1003

**Comment by mihall-primus** [comment]
So, I did some more testing.

CentOS 6 behaves the same as 7, i.e. no gateway is configured.

CentOS 5 doesn't seem to support IPADDR1, IPADDR2, etc. at all.  If I set them, no address is even applied to the interface.

**Comment by alvagante** [comment]
@ctrox looks pls check @mihall-primus notes.
Going to double check, will eventally revert.

**Comment by alvagante** [comment]
At a first grep on centos 7 network scripts it seems that ony GATEWAY is used.
On Redhat docs I didn't see mentions of GATEWAYn
Since it's just a variable settting, maybe we just could place both, but I would rather know where the GATEWAYn alternative is documented.

**Comment by alvagante** [comment]
Double checked, on CentOS 6 and CentOS 7 behaviour seem different.
On 7.7.1908 GATEWAY1 works, GATEWAY not.
