### ISSUE TITLE
Enhancement: Support for RHEL 7 on zLinux

### ISSUE THREAD

**Issue by SamDownton** [example42/puppet-network#177]
## Expected Behavior 
Red Hat have changed the interface scripts from 6 to 7 for configuring interfaces on s390x. The LAYER2="0/1" option now comes under OPTIONS="layer2=0/1". Therefore additional parameters and a change to the template are needed to use this module for RHEL 7 systems on s390x.

See:
[Adding a Network Device (RHEL 7)](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/sect-post-installation-adding-network-devices-s390.html)
&
[Adding a Network Device (RHEL 6)](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/ch-s390-Phase_1.html)

PR to come.

**Comment by alvagante** [comment]
thank you!
