### ISSUE TITLE
Incompatible with puppetlabs-concat 4+ on Debian

### ISSUE THREAD

**Issue by JayH5** [example42/puppet-network#182]
## Expected Behavior 
On Debian-based systems, the module works with `puppetlabs-concat` 4.0.0 and above. The `metadata.json` file claims that this module is compatible with that version.

## Actual Behavior
On Debian-based systems, the module does not work with `puppetlabs-concat` 4.0.0 and above. The following error (or similar) is seen during catalog compilation:
```
Evaluation Error: Error while evaluating a Resource Statement, Concat::Fragment[interface-eth0]: has no parameter named 'ensure' at .../vendor/network/manifests/interface.pp:647 ...
```

## Steps to Reproduce the Problem

  1. Update `puppetlabs-concat` to the latest version (currently 4.0.1)
  1. On a Debian-based system with `$network::config_file_per_interface` set `false`..
  1. Compile a catalog that includes a `network::interface` resource

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts): These are automated tests, I don't have the full output of `facter -p`
  1. Version of Puppet and of the module: Puppet: 4.10.1/4.10.6/5.1.0, network: 3.3.8, concat: 4.0.1
  1. The relevant Puppet code and eventually Hiera data: This is a bit of work for me to provide...

**Comment by jamesmollison** [comment]
Can confirm.  This error was introduced in #183 and is present in 3.3.8.

nodename.yaml
network::interfaces_hash:
  ens160:
    ipaddress: 'x.x.x.x'
    netmask: '255.255.255.224'
    gateway: 'x.x.x.x'

Produces this output. 
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Concat::Fragment[interface-ens160]: has no parameter named 'ensure' at /hidden/modules/network/manifests/interface.pp:647 on node nodename

This breaks a fairly vanilla config in debian/ubuntu

**Comment by alvagante** [comment]
Referenced commit should fix, please confirm when possible.

**Comment by JayH5** [comment]
@alvagante thank you! 🎉 Fix working for us.

**Comment by alvagante** [comment]
Ty , fyi the fixed version has been pushed to the forge.
