### ISSUE TITLE
Enhancement: Separate NAME= attribute in RedHat.erb to allow pretty names in NetworkManager

### ISSUE THREAD

**Issue by NiklausHofer** [example42/puppet-network#184]
## Expected Behavior 
It should be possible to have a `NAME=` attribute in the interface files on RHEL. That way, NetworkManager would show the connection without the `System` prefix.

Something like this in the `RedHat.erb` maybe:
```
<% if ! @con_name -%>
NAME="<%= @name %>"
<% else -%>
NAME="<%= @con_name %>"
<% end -%>
```

## Actual Behavior
Currently when I have an interface called `eth0`, `nmcli con show` will list it as `System eth0`. However, if I (manually) add the `NAME=foobar` attribute to the file, then `nmcli con show` wil show the connection as `foobar`.

## Steps to Reproduce the Problem

  1. Create an interface definition for interface `eth0`
  1. Run `nmcli con show`

**Comment by alvagante** [comment]
Fixed in the referenced commit. Added nm_name parameter to the network::interface define
