### ISSUE TITLE
Enhancement: Support customising the command used to restart interfaces when restart_all_nic=false

### ISSUE THREAD

**Issue by sf-mju** [example42/puppet-network#189]
In the project I am currently working on we would like to be able to customise the command used to restart interfaces that have changes.

In particular, when an interface is in the state link down we do not want the restart to run `ifup` as this generates an error code. We would like to change the restart command to be

`ifdown ${title}; ethtool ${title} | /usr/bin/grep 'Link detected' | if /usr/bin/grep -q 'yes'; then ifup ${title}; fi`

**Comment by alvagante** [comment]
The reload_command of the network::interface define allows you to customise the command to use when restarting network service.
