### ISSUE TITLE
How to configure default gateway device?

### ISSUE THREAD

**Issue by openface** [example42/puppet-network#191]
In templates/hostname-RedHat.erb I see there is support for GATEWAY but not for GATEWAYDEV. 

From the RHEL documentation:

GATEWAY=<value>, where <value> is the IP address of the network's gateway.
GATEWAYDEV=<value>, where <value> is the gateway device, such as eth0. Configure this option if you have multiple interfaces on the same subnet, and require one of those interfaces to be the preferred route to the default gateway.

In my case, I need to set a default route in a multiple network setup. Is this possible?   Thanks.

**Comment by alvagante** [comment]
@openface to customise the contents of /etc/sysconfig/network on RedHat you can provide a custom template via the network::hostname_file_template parameter.
