### ISSUE TITLE
OVSREQUIRES is unusable because of a typo

### ISSUE THREAD

**Issue by priteau** [example42/puppet-network#199]
## Expected Behavior 

The parameter OVSREQUIRES should be added to sysconfig/network-scripts file.

## Actual Behavior

OVSREQURIES is added instead.

## Steps to Reproduce the Problem

  1. Call network::interface with the ovsrequries parameter (which has a typo too).

## Specifications

This impacts the latest release (3.3.10).

**Comment by alvagante** [comment]
Thanks, PR merged
