### ISSUE TITLE
A few more typo fixes for README file

### ISSUE THREAD

**Issue by CyrilBrulebois** [example42/puppet-network#201]
Hi,

I'm attaching a few typo fixes for the README file, after (only) a quick glance at it. Most fixes are trivial, except for the very first one, as I'm not sure I captured the meaning properly. Please double-check that one in particular when considering merging the patch. ;)

[0001-Fix-typos-in-README.patch.txt](https://github.com/example42/puppet-network/files/1675217/0001-Fix-typos-in-README.patch.txt)

Cheers,
Cyril.

**Comment by alvagante** [comment]
Great, thanks, can you please submit a Pull Request via GitHub?
