### ISSUE TITLE
Are there any plans to support `netplan` with Ubuntu 18?

### ISSUE THREAD

**Issue by mdwheele** [example42/puppet-network#203]
Related: https://wiki.ubuntu.com/Netplan, https://wiki.ubuntu.com/MigratingToNetplan

If there is a better place for this type of question, let me know and I can close.

Netplan is an abstraction over NetworkManager / networkd. It uses YAML configuration files to specify supported backends and renders configs. It currently is released on Ubuntu 17.10 and will ship with Ubuntu 18.04 LTS.

Where does this module fit in that landscape? Would the advice be to disable management abstractions like Netplan and rely on the module? Or would expanding scope of this module to manage Netplan, itself (for Ubuntu systems) be a reasonable approach?

Mostly interested in discussion; no specific issue to report.

**Comment by alvagante** [comment]
Sorry for late reply here @mdwheele  
Intriguing question actually, will the "old" way of managing network settings still be supported in Ubuntu 18.04? If so , the module can still do its job , and it's up to the user to decide if to use netplan or not. If not, being this a modules supposed to manage network, specific support should be added.

**Comment by brwyatt** [comment]
The "old" way can technically still be used, as long as ifupdown is installed. Netplan also comes with a set of scripts to convert the old configs to netplan.

However, I don't believe it would be too difficult to generate the netplan config yaml file, and then set the `$service_restart_exec` to simply `netplan apply`.

**Comment by alvagante** [comment]
Support for legacy netowrking in Ubuntu 1804 is now present. Netplan configurations not supported.

**Comment by alvagante** [comment]
Netplan support will be added in version 4 of the module. 
https://github.com/example42/puppet-network/blob/version4/manifests/netplan/interface.pp
