### ISSUE TITLE
Service networking fails on Debian 9 with routes in ifup.d and ifdown.d --> module unusable on Debian 9

### ISSUE THREAD

**Issue by yasa1987** [example42/puppet-network#206]
Hello,
when routes are added in the ifup.d and ifdown.d on Debian 9 (stretch), the service **networking** cannnot start because at some point routes already exist. Following message appears :
> RTNETLINK answers: File exists

The same problems happen when the command **ifup -a --verbose** is executed. 
When executing **ifdown -a --verbose** the opposite message appears  :
> RTNETLINK answers: No such process

After analyzing the issue with the **--verbose** and reading the manpage, the command shows up following behavior :

1. Execute the ifup/ifdown script for each interface marked with "auto" in /etc/network/interfaces
2. Execute the ifup/ifdown script one more time with the "--all" parameter. **THIS IS THE POINT OF FAILURE**

In all ifup/ifdown Debian templates (route, mroute, rule), there is following line to determine if routes/rules should be added or not :
`if [ "$IFACE" = "<%= @interface -%>" ] || [ "$IFACE" = "--all" ]; then`

It makes the _route add_ or _route del_ commands executed twice when running ifup or ifdown for all interfaces. 
When I replaced the line with the following one, everything works perfectly :
`if [ "$IFACE" = "<%= @interface -%>" ]; then`

**Comment by alvagante** [comment]
Thanks for reporting, would you send a PR?

**Comment by yasa1987** [comment]
PR done!

**Comment by alvagante** [comment]
So it looks like this one is finally fixed. Thanks to everybody for the patient support
