### ISSUE TITLE
Hostname isn't set without gateway

### ISSUE THREAD

**Issue by baurmatt** [example42/puppet-network#208]
## Expected Behavior 
Using the following snippet on a CentOS maschine should configure the hostname:

```puppet
class { '::network':
  hostname => $::fqdn,
}
```

## Actual Behavior
Nothing happens

## Steps to Reproduce the Problem
Use snippet from above

## Specifications
Problem is that the hostname gets only configured if the gateway gets configured as well.
https://github.com/example42/puppet-network/blob/master/manifests/init.pp#L265

This should at least fail.

**Comment by alvagante** [comment]
fixed in the referenced commit

**Comment by baurmatt** [comment]
Thanks! :)
