### ISSUE TITLE
Wrong interface restarts

### ISSUE THREAD

**Issue by gregoryo2014** [example42/puppet-network#210]
## Expected Behavior 

With `restart_all_nic == false` and `config_file_per_interface == false`, changing the detail of an interface should cause just that interface to restart.

## Actual Behavior

A different interface restarts.

## Steps to Reproduce the Problem

  1. `vim /etc/network/interfaces`, change a setting e.g. dhcp to manual on `br-mesh`
  1. Run Puppet.
  1. `br-mesh` changes from manual back to dhcp and restarts `br-mgmt`
```Info: /Stage[main]/Network/Network::Interface[br-mgmt]/Concat[/etc/network/interfaces]/File[/etc/network/interfaces]: Filebucketed /etc/network/interfaces to puppet with sum 20bae5d666a7c942a930735c71e1b287
Notice: /Stage[main]/Network/Network::Interface[br-mgmt]/Concat[/etc/network/interfaces]/File[/etc/network/interfaces]/content: 

Notice: /Stage[main]/Network/Network::Interface[br-mgmt]/Concat[/etc/network/interfaces]/File[/etc/network/interfaces]/content: content changed '{md5}20bae5d666a7c942a930735c71e1b287' to '{md5}7def54530f9e4e5aa14e659de8d060de'
Info: Concat[/etc/network/interfaces]: Scheduling refresh of Exec[network_restart_br-mgmt]
```
## Specifications

  * Output of ```facter -p``` on the failing node (at least the OS related facts)
```
# facter -p os
{
  architecture => "amd64",
  distro => {
    codename => "xenial",
    description => "Ubuntu 16.04.4 LTS",
    id => "Ubuntu",
    release => {
      full => "16.04",
      major => "16.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
  },
  selinux => {
    enabled => false
  }
}
```
  * Version of Puppet and of the module
```
# puppet --version
4.10.10
```
```
# grep network Puppetfile 
mod 'example42-network', '3.3.10'
```
  * The relevant Puppet code and eventually Hiera data
```
network::config_file_per_interface: false
network::default_interfaces_hash:
  restart_all_nic: false
```

**Comment by gregoryo2014** [comment]
Could it be because the device is a bridge (thus the br- moniker)?

**Comment by alvagante** [comment]
Reading better the description, it looks like the behaviour is what's expected: you change manually an interface setting (on br-mesh) and that's the interface that puppet restarts. Going to close the issue.

**Comment by gregoryo2014** [comment]
> and that's the interface that puppet restarts

Actually, the description of the issue explicitly states that a different interface restarts.

In any case, we worked around this bug for a time, and then moved on when Ubuntu gave us a gentle push toward Netplan.

**Comment by alvagante** [comment]
@gregoryo2014 oops sorry, you are right. Didn't read well br-mesh and br-mgmt. Suppose it could be due to the fact that they are bridged interfaces, as you suggested. Wound if the same issue would appear using network::config_file_per_interface: true.
Anyway, issue closed. Will reopen in case a similar issue is arised again.
