### ISSUE TITLE
It should be possible to create IPv6 routes for RedHat based systems

### ISSUE THREAD

**Issue by TorLdre** [example42/puppet-network#213]
## Expected Behavior 
When creating routes with route.pp and specify "inet6" with the family parameter, routes should be created for IPv6.

## Actual Behavior
For RedHat based systems, the family parameter has no effect, and routes are written to route-${name}, creating errors when trying to bring up interface.

## Steps to Reproduce the Problem

  1.  Create an IPv6 based route on a RedHat-based system
  2.  Observe puppet write the route to route-${name} instead of route6-${name}
  3.  Observe error messages as RedHat tries to bring up an IPv4 route with IPv6 parameters  

## Specifications

Please add this info:

  1. Tested on CentOS 7.4, should be similar to RHEL 6.x/7.x and derivates  
  2. Tested on puppet 4.x
  3. I will suggest code via a pull request

**Comment by alvagante** [comment]
Suppose this can be closed now
