### ISSUE TITLE
Feature request : add ovs_ports option for network::interface

### ISSUE THREAD

**Issue by arteal** [example42/puppet-network#220]
Hello, 

can we please add support for ovs_ports option for interfaces? Funcitionality is described in :
https://github.com/openvswitch/ovs/blob/master/debian/openvswitch-switch.README.Debian#L64

Pull request is on the way. Thanks

**Comment by alvagante** [comment]
Ping @arteal , please check the comment in the pr

**Comment by alvagante** [comment]
PR merged, added other ovs options for Debian
