### ISSUE TITLE
Deprecation of the Example42/puppet-network module

### ISSUE THREAD

**Issue by igarny** [example42/puppet-network#222]
Dear Allesandro,

First of all apologies for giving here advices...
Following the discussion in this thread https://github.com/example42/puppet-network/pull/214#issuecomment-376208094, I see it is hard to maintain the module and at the same time not disappoint more than 46k subscribers.
Of course maintenance of an outdated work and ideas cannot scale with future work and progress. 
Obviously people still find the module stable and flexible enough and despite the limitations posed this module is still attractive. Finally the only way forward for progress is to do change....

I see 2 ways out from this situation:
- Puppet themselves realize the importance and the need for such an implementation
- Example42 propose a better solution for the network management.

I would guess the best strategy for you guys is to propose an alternative module, before deprecating this one. Also the sooner this happens, the better, since it is not clear if this module will work with Puppet 6.x releases. I guess any proposal will work, but with time, if the new proposal fails, there will be others with alternatives.

I guess the community / current contributors will also be interested to propose improvements and fixes.
So I will be looking forward for your improved release with native support for IPv4 and IPv6 management. Currently I have a small wrapper around this module to manage Debian networking, which I guess everyone has.

Regards,
Ivan Garnizov

**Comment by alvagante** [comment]
Thanks for the advice @igarny , I'm actually ashamed, and responsible, for the situation and the current status of the network module. And I'm sorry for the bad service done to the community.
I'd propose the following: we start to actively look for maintainers of the network module, and work more to integrate backwards compatible PR and decent ipv6 support.
No immediate deprecation, it was never intended to be.

A total rewrite will probably be done as a psick profile, in a different namespace compatible with this or any alternative module.

Official network module will become whatever Puppet decide.

Does it sound reasonable?

**Comment by igarny** [comment]
Hello Allesandro,

Thank you for your prompt reply. Please note my intention was never to finger point nor to seek for the reasons for the current situation. My apologies, if I did not manage to express myself like it.
Also apologies for abusing the issue tracker....I guess this is not the correct way to discuss these matters.

WRT the module: 
Te puppet-network module is shared with the community and no one is forced to use it. The reputation you have in Puppet forge is not based on the color of your eyes. It is just that it has a good approach and no one could / has shared anything better. It is interesting you have gained this popularity despite the lack of good documentation (I had opened a ticket in the past about it, even Puppet Forge has remarks)
Nevertheless I find the code readable....or at least to the point I am interested in.

IMO the only thing we (the community) can improve is to provide documentation / explanation on the usage and implementation of the proposed features in the pull requests being raised unless these are really bug fixes. We should try to minimize the effort needed to support the module.

Please note I have merely given an example of a configuration statement for management of Debian network interfaces. Still the example is valid. I will try to write more about it.

WRT the finding of a maintainer I am afraid to give any advice here.

Regards,
Ivan

**Comment by alvagante** [comment]
Hei @igarny we had some internal discussion and we realized that we can't just give up with the module and abandon its users, so we decide to invest more time and resources on it and start to maintain it more actively. So going to close this issue, which actually has had a big result: clear our minds on our intentions on the module and give it more love.
Thank you for raining the point, and I hope to keep on receiving your contributions. Next plans is to flush the PR and tickets list, improve documentation and then decide how to cope with next major release and backwards compatibility.
