### ISSUE TITLE
ip rule config management for Debian does not support IPv6 in both the manifest and the templates

### ISSUE THREAD

**Issue by igarny** [example42/puppet-network#225]
## Expected Behavior 

"ip -6 rule " statements

## Actual Behavior

"ip rule " statements only

## Specifications
Check these:
https://github.com/example42/puppet-network/blob/master/templates/rule_up-Debian.erb
https://github.com/example42/puppet-network/blob/master/templates/rule_down-Debian.erb

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
  1. Version of Puppet and of the module
  1. The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
Suppose this can be closed now,
