### ISSUE TITLE
Name of variables within templates are incorrect

### ISSUE THREAD

**Issue by beergeek** [example42/puppet-network#239]
## Expected Behavior 
When setting either `network::interface::options_extra_redhat`, `network::interface::options_extra_debian`, or `network::interface::options_extra_suse` the hash keys and values should appear in the relevant configuration files.

## Actual Behavior

The variables within the templates are incorrect, therefore the data is never written to file.

## Steps to Reproduce the Problem

  1.  set `network::interface::options_extra_redhat`
  1. run puppet
  1. observe on 'extra' values in the NIC configuration file

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts) os.family = RedHat os.name = CentOS
  1. Version of Puppet and of the module: puppet 5.5.3 and module 3.4.4
  1. The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
omg, thanks!
