### ISSUE TITLE
Add support for multipath routes (ECMP)

### ISSUE THREAD

**Issue by odivlad** [example42/puppet-network#244]
Hi all.

Actually, in our case is useful to add support for multipath routes (ECMP). They should look like:
```
# cat /etc/sysconfig/network-scripts/route-eth0
default nexthop via 1.1.1.1 nexthop via 1.1.1.2
# ip r
default
	nexthop via 1.1.1.1  dev eth0 weight 1
	nexthop via 1.1.1.2  dev eth0 weight 1
```

This is useful when you want to balance egress traffic for two different GWs.
I already have a small patch for this with RedHat templating:
https://github.com/odivlad/puppet-network/commit/59be933a36b26ee4373c4c4716f1d40fbef8206f
We currently use it from our fork and it works fine.

Maybe somebody would be interested in such behaviour too, so I can prepare PR.
Looking to hear your opinions.

**Comment by alvagante** [comment]
Looks ok, please send a PR with support for the other distros as well
