### ISSUE TITLE
Configure Debian interface with both ipv4 and ipv6 address

### ISSUE THREAD

**Issue by Freeaqingme** [example42/puppet-network#248]
## Expected Behavior 

Typically I configure my networking on Debian (oh, well, Ubuntu 1804) as follows:
```
allow-hotplug ens3

auto ens3
iface ens3 inet static
	address  136.x.y.z
	netmask  255.255.255.0
	gateway  136.x.y.z

iface ens3 inet6 static
	address 2a01:XXX:YYY:ZZZ::1
	netmask 48
	gateway 2a01:XXX:YYY::1
```

Tne network::interface type allows to specify a family, but I can't specify both an ipv4 address and ipv6 address on the same interface?

I think it would be ideal to be able to specify in the following fashion, though i'm not sure how compatible that would be with the current code base. Alternatives surely would be possible as well (and perhaps what I'm looking for has already been implemented and I'm simply not seeing it).

```
  network::interface { 'foo':
    interface => 'eth0',
    ipaddress => $::facts['networking']['interfaces']['eth0']['bindings'][0]['address'],
    netmask   => $::facts['networking']['interfaces']['eth0']['bindings'][0]['netmask'],
  }

  network::interface { 'bar':
    name => 'eth0',
    family => 'inet6',
    ipaddress => $::facts['networking']['interfaces']['eth0']['bindings6'][0]['address'],
    netmask   => $::facts['networking']['interfaces']['eth0']['bindings6'][0]['netmask'],
  }
```

**Comment by alvagante** [comment]
The code you wrote looks fine, doesn't it work with current module?

**Comment by alvagante** [comment]
More precisely, using different titles for each interface and the interface parameter (not the name one, which currently doesnt exist). Different files should be created (according to title) but the same interface should be managed fir ipv4 and ipv6.
