### ISSUE TITLE
Failure to bring up additional interfaces

### ISSUE THREAD

**Issue by stephenkenny** [example42/puppet-network#253]
## Expected Behavior 
When adding an extra interface for a node via Hiera, Puppet agent should bring up that interface on the node.

## Actual Behavior
Agent fails with the following error:

```Error: /Stage[main]/Network/Exec[/sbin/ifdown -a --force ; /sbin/ifup -a]: '/sbin/ifdown -a --force ; /sbin/ifup -a' returned 1 instead of one of [0]```

I note that I can bring the interface up manually with the following command:

```ifconfig eno2 up```

(I should say that I am not very clear on the differences between ```ifup``` and ```ifconfig <interface> up```)

## Steps to Reproduce the Problem

  1.  Add the yaml data for the interface on the Puppet server:
  1.  Run the `Puppet agent` on the node

## Specifications
Here's my yaml data for the extra interface:

```
eno2:
    'interface': 'eno2'
    'type': 'Ethernet'
    'allow_hotplug': 'eno2'
    'family': 'inet' 
```

## Additional Information
  1. Puppet version: 5.5.3
  1. example42-network  module version: v3.5.0

Here's the OS-related facter output:
```os => {
  architecture => "amd64",
  distro => {
    codename => "stretch",
    description => "Debian GNU/Linux 9.5 (stretch)",
    id => "Debian",
    release => {
      full => "9.5",
      major => "9",
      minor => "5"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "9.5",
    major => "9",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}```

Thanks for any help you can provide.

Kind regards,
Stephen Kenny
Trinity College
Dublin
Ireland

**Comment by alvagante** [comment]
So, it look like one of the commands /sbin/ifdown -a --force  or  /sbin/ifup -a fails in your setup.
You might try to run then manually on your system and see if they give more info.
Error might be due by wrong network configurations either managed by Puppet or not.,
