### ISSUE TITLE
ipv6 route issue (undefined method `encoding')

### ISSUE THREAD

**Issue by AxisNL** [example42/puppet-network#255]
The module works fine, except for trying to set ipv6 routes.

## Expected Behavior 

I use this puppet code to set a default ipv6 route:

```
  network::route { 'eth0':
    ipaddress => [ '::', ],
    netmask   => [ '0', ],
    gateway   => [ '2001:41d0:0203:14ff:ff:ff:ff:ff', ],
    family    => [ 'inet6', ],
  }
```

I would expect it to set the following contents in the file /etc/sysconfig/network-scripts/route6-eth0:

`default via 2001:41d0:0203:14ff:ff:ff:ff:ff`

## Actual Behavior

I get an error:

```
# puppet agent -t --noop
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, undefined method `encoding' for #<ArgumentError: invalid address> (file: /etc/puppetlabs/code/environments/production/modules/network/manifests/route.pp, line: 151, column: 14) (file: /etc/puppetlabs/code/environments/production/manifests/server-23.pp, line: 49) on node server-23.domain.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

## Steps to Reproduce the Problem

  1.  Put the above code in manifest
  2.  Run puppet agent

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)

```
# facter -p os
{
  architecture => "x86_64",
  distro => {
    codename => "Core",
    description => "CentOS Linux release 7.5.1804 (Core)",
    id => "CentOS",
    release => {
      full => "7.5.1804",
      major => "7",
      minor => "5"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.5.1804",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}
```

  1. Version of Puppet and of the module

puppetserver version: 5.3.6
puppet agent version: 5.5.8
module example42-network (v3.5.0)
 
 1. The relevant Puppet code and eventually Hiera data

only above code, no hiera is used.

**Comment by benibr** [comment]
I ran into the same problem using

    puppetserver version: 5.3.1
    puppet agent --version: 5.5.8
    module example42-network (v3.5.0)

and puppetcode something like the following puppetcode which I took from the examples in https://github.com/example42/puppet-network/blob/master/manifests/route.pp

    network::route { $interface:
        ipaddress => [ '::' ],
        netmask   => [ '0' ],
        gateway   => [ 'fefe::23' ],
        family    => [ 'inet6' ],
    }

However I end up with the same error as @AxisNL and therefore had a look into  `modules/network/manifests/route.pp, line: 151, column: 14` which point to the `build_cidr_array` function:

    if $cidr {
      validate_array($cidr)
      $_cidr = $cidr
    } else {
      $_cidr = build_cidr_array($netmask)
    }

So I worked around this by adding the CIDR directy to the Resource:

    network::route { $interface:
        ipaddress => [ '::' ],
        netmask   => [ '0' ],
        cidr      => [ '0' ],
        gateway   => [ 'fefe::23' ],
        family    => [ 'inet6' ],
    }

**Comment by alvagante** [comment]
Closing the issue , the mentioned commit should fix this
