### ISSUE TITLE
Validate the value of the 'ensure' parameter

### ISSUE THREAD

**Issue by iaingeorgeson** [example42/puppet-network#257]
Hello,

I realise that there's no reason for anyone to do this in the first place. But we did somehow, and the error message was confusing so I'm raising the issue. I'm not expecting this to work, just a more understandable error message.

## Expected Behavior 

When a network::interface resource is given a parameter  `ensure => 'up'`, the value should be recognised as invalid and an appropriate error thrown.

## Actual Behavior

Error: Failed to apply catalog: Validation of File[/etc/sysconfig/network-scripts/ifcfg-enp6s0f0] failed: You cannot specify more than one of content, source, target at /path/to/network/manifests/interface.pp:713

This is because the $ensure parameter is passed on to the file "/etc/sysconfig/network-scripts/ifcfg-${name}" resource, where it is interpreted as a symlink target.

## Steps to Reproduce the Problem

  1. Configure an interface with

```
network::interfaces_hash:
    enp6s0f0:
     ensure: up
     ipaddress: 10.n.n.n
     netmask: 255.255.128.0
     gateway: 10.n.n.n
```

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)

```
os => {
  architecture => "x86_64",
  distro => {
    codename => "Core",
    description => "CentOS Linux release 7.5.1804 (Core)",
    id => "CentOS",
    release => {
      full => "7.5.1804",
      major => "7",
      minor => "5"
    },
    specification => ":core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.5.1804",
    major => "7",
    minor => "5"
  },
  selinux => {
    config_mode => "enforcing",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "31"
  }
}

```
  2. Version of Puppet and of the module

Puppet 4.10.12
https://github.com/example42/puppet-network 3.5.0

  3. The relevant Puppet code and eventually Hiera data

See above

Thanks,

**Comment by alvagante** [comment]
Fixed the issue in the referenced commit, sorry for the extreme delay
