### ISSUE TITLE
support for promiscuous mode 

### ISSUE THREAD

**Issue by edmaher** [example42/puppet-network#260]
## Expected Behavior 
Populate the ifcfg file with 
PROMISC=yes

## Actual Behavior
presently not supported on any platform
Believed to be supported on SUSE, RedHat and Debian based systems according to 30 second Google search.

## Steps to Reproduce the Problem
N/A

## Specifications
in hiera, specify network_interface attribute
promisc:yes

**Comment by alvagante** [comment]
@edmaher please check the above PR
