### ISSUE TITLE
Support for PREFIX

### ISSUE THREAD

**Issue by mrolli** [example42/puppet-network#263]
We are used to use PREFIX instead of NETMASK in our interface configuration files (CentOS servers). Your module does not support PREFIX. Do you think your module should support the PREFIX setting too? For me, using prefixes instead of masks is handier.

**Comment by alvagante** [comment]
Can be added , with a commit like this https://github.com/example42/puppet-network/pull/238/files

**Comment by mrolli** [comment]
Ok, ok, I'll do it. ;-)
