### ISSUE TITLE
ifupdown2

### ISSUE THREAD

**Issue by JOJ0** [example42/puppet-network#268]
Hi, I am having problems using the ifupdown package in Ubuntu 18.04 (ifdown, ifup errors like this: "ifdown: interface ens3 not configured"). As soon as I install ifupdown2, my problems are gone. Is it possible/configurable to tell the network module that it should ensure package ifupdown2 instead of ifupdown?
Thanks and all the best
Jojo

**Comment by JOJ0** [comment]
Currently my dirty workaround is to hardcode ifupdown2 into your modules code (params.pp). My previous workaround was to ensure ifupdown2 (which uninstalls ifupdown) in one of my puppet profiles, the one which I use to install packages I want on all my systems. This actually leads puppet to constantly uninstalling ifupdown and installing ifupdown2 and vice versa. Obviously not a good workaround.

As far as I understand ifupdown2 is only a rewrite in python of ifupdown. I'd like to suggest you just let the puppet user choose wether he wants the module use ifupdown or ifupdown2 via a class/hiera variable. Do you think this is possible? I am only familiar with writing puppet profile and If I would have ever written a module I would just send you a pull request. Maybe I should start now...? ;-)
Thanks!
all the best
Jojo

**Comment by alvagante** [comment]
A parameter could be ok, even if, if normal ifupdown doesn't work on Ubuntu 18.04 maybe is better to forge (by default) the usage of ifupdown2 where needed

**Comment by alvagante** [comment]
It's possible to configure the command to use to restart network. 
On hiera you can do something as follows:```
```
# this is the default for Debian derivatives
network::service_restart_exec: '/sbin/ifdown -a --force ; /sbin/ifup -a' 
```
