### ISSUE TITLE
SLES 15 support

### ISSUE THREAD

**Issue by towo** [example42/puppet-network#271]
## Expected Behavior 

SLES 15 is supported.

## Actual Behavior

SLES 15 is not supported.

## Steps to Reproduce the Problem

  1. Use on SLES 15.
  2. `bootproto` will not be set to static when intended to be set.

## Notes

I'll be submitting a PR as a follow-up.

**Comment by towo** [comment]
cf #272

**Comment by kenyon** [comment]
Looks like this issue can be closed.

**Comment by towo** [comment]
I'll just take the liberty of closing it since it was merged to master.
