### ISSUE TITLE
Ubuntu Xenial ip route show

### ISSUE THREAD

**Issue by elmobp** [example42/puppet-network#277]
On Xenial, when you apply the route up/down scripts if you are looking for 0.0.0.0/0 it will fail as default is returned rather than 0.0.0.0/0, I have a PR coming that will fix the logic for default on Debian and use PCRE on the grep

**Comment by jamesmollison** [comment]
This will also partially fix #256 

Currently this module is broken on Ubuntu when using ip-route scripts.

**Comment by jamesmollison** [comment]
This is the syntax error reported in #256 - the current release (3.5.1) of this module is causing networking to behave unreliably in ubuntu 16.04.

**Comment by alvagante** [comment]
Published v3.5.2 to the Forge with the fix, sorry for latency
