### ISSUE TITLE
resource notification cannot be disabled in network::conf

### ISSUE THREAD

**Issue by findmyname666** [example42/puppet-network#290]
## Expected Behavior
I expect to use `network::conf` without necessity to notify any resources when network configuration file is created. Right now `network::conf` always notify/refresh `class_default`. There are following comments:
```
# [*config_file_notify*]
#   String. Optional. Default: 'class_default'
#   Defines the notify argument of the created file.
#   The default special value implies the same behaviour of the main class
#   configuration file. Set to undef to remove any notify, or set
#   the name(s) of the resources to notify
```
Params `$config_file_notify` cannot be set to `undef` - puppet always use default value when provided parameter is `undef`.

Default value for `$config_file_notify` should be `undef/absent` as per puppet design.

## Actual Behavior
When params `$config_file_notify` is set to `undef/NULL` default value is used e.g. `class_default` and it is refreshing/notifying `network` class:
```
 Scheduling refresh of Exec[/sbin/ifdown -a --force ; /sbin/ifup -a]
```

## Steps to Reproduce the Problem

  1. Create some simple configuration with network::conf and set `$config_file_notify` to `undef`:
```
  network::conf { 'e1000e':
    owner                      => 'root',
    group                       => 'root',
    mode                        => '0755',
    template                  => 'some_module/some_template.erb',
    path                          => '/etc/network/if-up.d/some_conf_file,
    config_file_notify  => undef,
    options_hash          => { 'some_key' => true },
  }
```

## Specifications

Puppet version: 6.4.2
Network module version: 3.5.2

**Comment by alvagante** [comment]
@findmyname666 can you double check if the PR fixes both  #290 and #289 ?

**Comment by findmyname666** [comment]
Hi @alvagante, 

I tried a commit `169a336ebc6446246662c9c668ff2283f849f02b` and now `config_file_notify` can be set to false and it works as expected.

BUT it cannot be set to undef as it is not a valid resource reference:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: No title provided and "undef" is not a valid resource reference (file: /etc/puppetlabs/code/modules/network/manifests/conf.pp, line: 120) on node test02.de.showmax.cc
```

Furthermore i created some comments in an above comment.

Thx

**Comment by findmyname666** [comment]
Hi @alvagante, 
When i set 'undef' in hiera it fails on:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: No title provided and "undef" is not a valid resource reference (file: /etc/puppetlabs/code/modules/network/manifests/conf.pp, line: 128) on node ...
```
It is failing here (lines can be shifted in my patched version):
```
119   file { "network_conf_${name}":
120     ensure  => $ensure,
121     source  => $source,
122     content => $manage_content,
123     path    => $manage_path,
124     mode    => $manage_mode,
125     owner   => $manage_owner,
126     group   => $manage_group,
127     require => $manage_require,
128     notify  => $manage_notify,
129   } 
```
The reason is that 'undef' from hiera is converted into string therefore it goes through 'default' option:
```
  $manage_notify  = $config_file_notify ? {
    'class_default' => $::network::manage_config_file_notify,
    true            => $::network::manage_config_file_notify,
    false           => undef,
    undef           => undef,
    default         => $config_file_notify,
  }
```
To solve it we can use 'undef' as string:
```
  $manage_notify  = $config_file_notify ? {
    'class_default' => $::network::manage_config_file_notify,
    true            => $::network::manage_config_file_notify,
    false           => undef,
    'undef'           => undef,
    default         => $config_file_notify,
  }
```
I see that this modules use such case already see [here](https://github.com/example42/puppet-network/blob/master/manifests/init.pp#L169). Furthermore I don't see reason why use `undef           => undef,` (without apostrophes) as it should fall into default option.

**Comment by alvagante** [comment]
@findmyname666 +1 for your suggestion. Would you submit a PR?
Have you tried to use a tilde in hiera? (that should be the way to "submit" and undef).
Incidentally, all this undef management is quite a pain, would do things differently if I could start from scratch

**Comment by findmyname666** [comment]
@alvagante your PR is OK but i would drop `undef` from it at all ... the user can disable it with `false` ... + there is a typo in comment for :
```
# [*config_file_require*]
#   String or Boolean. Optional. Default: 'class_default'
```
The default value is undef per the [code](https://github.com/example42/puppet-network/blob/master/manifests/conf.pp#L74).
Furthermore If you insist i can create a PR.

**Comment by findmyname666** [comment]
@alvagante can we make into master as soon as possible pls?

**Comment by alvagante** [comment]
Done, closing the issues
