### ISSUE TITLE
Support EL8

### ISSUE THREAD

**Issue by florianfa** [example42/puppet-network#292]
## Expected Behavior
Network Module should successfully restart network service on RHEL 8 / Centos 8

## Actual Behavior
Error: /Stage[main]/Network/Exec[service network restart]: Failed to call refresh: 'service network restart' returned 5 instead of one of [0]

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
  1. Version of Puppet and of the module
  1. The relevant Puppet code and eventually Hiera data

**Comment by FcoCalero** [comment]
Hi, 

Im having the same issue and still can't explain why, but if you run a second time, it doens't complain anymore.

Regards

**Comment by FcoCalero** [comment]
I noticed the following

service network status
Redirecting to /bin/systemctl status network.service
Unit network.service could not be found.

And it is explained in 
https://www.golinuxcloud.com/unit-network-service-not-found-rhel-8-linux/

**Comment by FcoCalero** [comment]
I see two solutions, the easy and the good one.

The easy is 
yum install network-scripts

That will provided the old stuff needed to make the current version of this module works

The good one
Add new code to allow to the module manage interfaces with NetworkManager

**Comment by njegosrailic** [comment]
I vote for the good one. Seems like everything works we just need to set correct service name for `service_restart_exec`. Will check and probably put an PR soon.

**Comment by FcoCalero** [comment]
Already did a PR, waitting feedback

**Comment by florianfa** [comment]
> Hi,
> 
> Im having the same issue and still can't explain why, but if you run a second time, it doens't complain anymore.
> 
> Regards

Hello FcoCalero,

this is because the restart of the network stack would be only triggered once if the network configuration file changes. On the second run no change happens to the network config file therefore no restart would be triggered.

Regards,
Florian

**Comment by alvagante** [comment]
Looks like NetworkManager is the default network management service in rhel8, but I wonder how many use it on servers. Note also, that the network::service_restart_exec parameter allows customisation of the command to run to restart the service. So with the current module it's actually possible to configure the correct service restart command, whatever is the method used.

**Comment by alvagante** [comment]
Merged in https://github.com/example42/puppet-network/pull/299
