### ISSUE TITLE
Release 3.5.2 on Puppet Forge contains .git

### ISSUE THREAD

**Issue by a3li** [example42/puppet-network#298]
The 3.5.2 release on the Forge contains your `.git` directory, making it quite a bit larger than the previous release. r10k seems to be really inefficient at unpacking, so deploying with 3.5.2 takes quite a while, causing hosts to be intermittently unable to find the deployed module.

```
❯ ls -lisah example*
6184575   64 -rw-r--r--@ 1 alex  staff    32K 19 Dez 15:40 example42-network-3.5.1.tar.gz
6184543 1824 -rw-r--r--@ 1 alex  staff   865K 19 Dez 15:40 example42-network-3.5.2.tar.gz
```

**Comment by alvagante** [comment]
Just pushed version 3.5.3, without the  .git dir
