### ISSUE TITLE
Input check. Verify that the ip address is a valid one.

### ISSUE THREAD

**Issue by pier4r** [example42/puppet-network#304]
## Expected Behavior 
If a puppet operator has a typo and passes a wrong ip address, the ip address is **tested** for validity and then rejected in the case it is not valid.

## Actual Behavior
If a puppet operator makes a typo and passes a wrong ip address, the ip address is silently accepted and can crash the system.

## Steps to Reproduce the Problem

  * With the following setup
```
class {'network':
    interfaces_hash => {
        eth0 => {
            ipaddress => '10.18.99.323', #it can be even '10.18.99.23.23' or any other typo
            netmask   => '255.255.0.0',
            gateway   => '10.18.0.254',
        }
    },
}
```
  * Then let the puppet node run on the target, and see the target disconnect itself.

## Specifications

Please add this info:

  * OS related facts (although the problem is OS independent)
```
# facter os
{
  architecture => "x86_64",
  distro => {
    codename => "Core",
    description => "CentOS Linux release 7.7.1908 (Core)",
    id => "CentOS",
    release => {
      full => "7.7.1908",
      major => "7",
      minor => "7"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.7.1908",
    major => "7",
    minor => "7"
  },
  selinux => {
    enabled => false
  }
}
```
  1. Version of Puppet and of the module
```
# puppet --version
4.10.12

mod "example42/network", "3.5.3"
```
  - The relevant Puppet code and eventually Hiera data. See above.

**Comment by pier4r** [comment]
I am not 100% sure but I guess the ipaddress check should go here: https://github.com/example42/puppet-network/blob/master/manifests/interface.pp (the class is already a validate fest) and since this module relies on stdlib, there are the types that one can use for validation (although they may not be working in cas eof legacy codebase).

For example: https://github.com/puppetlabs/puppetlabs-stdlib/blob/v6.2.0/REFERENCE.md#stdlibipaddressv4

Thus the check would be something like

```
if $ipaddress =~ Stdlib::IP::Address::V4
```

**Comment by alvagante** [comment]
The current version of the module still supports Puppet 3, where data types are not supported.
The next version, still not released, will prop puppet 3 support and has similar checks (https://github.com/example42/puppet-network/blob/version4/manifests/interface.pp)
