### ISSUE TITLE
Question: confusion about RHEL 8/CentOS 8 support

### ISSUE THREAD

**Issue by corporate-gadfly** [example42/puppet-network#305]
For a CentOS system `CentOS Linux release 8.1.1911 (Core)`, what is the recommended sequence? It is unclear in the documentation, so my apologies for the newbie question.

  1. Should the package for `NetworkManager` be uninstalled?
  1. Should the package for `network-scripts` be installed?
 
If someone has a working setup with multiple interfaces (eth0/eth1) and ip rules and routes and are able to share that would be appreciated.

I can share other details upon request. Currently using version `3.5.3` with puppet `6.12.0`.

**Comment by alvagante** [comment]
The module should work as expected using NetworkManager (configured via the "usual" scripts in /etc/sysconfig/network-scripts ).
Here's some sample hieradata:
```
network::interfaces_hash:
  'eth0':
    enable_dhcp: true
  'eth1':
    ipaddress:
      - '10.42.43.104'
      - '10.42.143.104'
    netmask: '255.255.255.0'
    gateway: '10.42.143.1'
network::mroutes_hash:
  eth1:
    routes:
      '10.42.50.0/24': '10.42.43.1'
      '10.42.100.0/24': '10.42.43.1'
      '10.42.251.0/24': '10.42.43.1'
```
