### ISSUE TITLE
Allow to set IPV6_AUTCONF in global /etc/sysconfig/network

### ISSUE THREAD

**Issue by mat1010** [example42/puppet-network#310]
Puppet version: 6.14.0
Module version: v3.5.3
OS: Centos 7.7

I would like to set IPV6_AUTCONF globally instead of an per interface basis. Right now the parameter is not handled by the network class. If you are ok with this, I will open  the corresponding PR.

## Expected Behavior 

```
class { 'network':
  hostname      => "example.org",
  ipv6_autoconf => "no",
}
```
`/etc/sysconfig/network` should result in
```
# File Managed by Puppet
NETWORKING="yes"
HOSTNAME="example.org"
IPV6_AUTOCONF="no"
```

## Actual Behavior
`/etc/sysconfig/network` results in
```
# File Managed by Puppet
NETWORKING="yes"
HOSTNAME="example.org"
```

**Comment by alvagante** [comment]
@mat1010 as long as the PR doesn't change the current behaviour by default (if you set the param, the change is reflected on the /etc/sysconfig/network file, othewise things remain as before), that's ok 
Would also be nice to have it working for Debian derivatives as well, if possible

**Comment by mat1010** [comment]
@alvagante Thanks - the PR  #311 has been created. As far as I can see, from a documentation perspective, there's no such global option for Debian, it looks like this can only be done per interface.

**Comment by alvagante** [comment]
@mat1010 merged, thank you
