### ISSUE TITLE
network::rule family defaulting to undef wipes rule-* files in RH distros when upgrading from older versions

### ISSUE THREAD

**Issue by unrulyv** [example42/puppet-network#318]
## Expected Behavior 
Upgrading from old versions (in our case, 3.3.2 to 3.5.3) should preserve our existing routes and rules.

## Actual Behavior
The rule files (/etc/sysconfig/network-scripts/rule-*) had their content wiped. 

## Steps to Reproduce the Problem

  1. Upgrade puppet-network module from 3.3.2 to 3.5.3
  2. Example hiera for network::rules:

network::routes_hash:
  em3:
    ipaddress:
      - '172.26.2.0'
      - '0.0.0.0'
    gateway:
      - '172.26.2.10'
      - '172.26.2.1'
    netmask:
      - '255.255.255.0'
      - '0.0.0.0'
    table:
      - '1'
      - '1'
  3. /etc/sysconfig/network-scripts/rule-em3 file in v3.3.2:
```
from 172.26.2.0/23 table 1 priority 100
```
Same file in v3.5.3: empty

The reason is that v3.5.3 has network::rule `family` defaulting to undef: https://github.com/example42/puppet-network/blob/master/manifests/rule.pp#L31

And the RedHat template checks if `family` is defined before doing anything: https://github.com/example42/puppet-network/blob/master/templates/rule-RedHat.erb#L5

The fix should be simple: setting a default value for network::rule::family, just like here: https://github.com/example42/puppet-network/blob/master/manifests/route.pp#L115

**Comment by benibr** [comment]
I think this could be resolved by deleteing the `@family` in https://github.com/example42/puppet-network/blob/master/templates/rule-RedHat.erb#L5 or by setting the family parameter to a valid default.

Any suggestions?

**Comment by alvagante** [comment]
@unrulyv I'm so sorry such a late feedback on this. Got out of the radar. Thanks @benibr for the ping and the suggestion.
 Can you check if the linked fix works?

**Comment by benibr** [comment]
No it does not :-/

```
Info: Using configured environment 'DAE_14880'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error 
while evaluating a Function Call, Failed to parse template network/rule-RedHat.erb:
  Filepath: /etc/puppetlabs/code/environments/DAE_14880/modules/external/network/templates/rule-RedHat.erb
  Line: 5
  Detail: undefined method `[]' for nil:NilClass
 (file: /etc/puppetlabs/code/environments/DAE_14880/modules/external/network/manifests/rule.pp, line: 51, column: 20) (file: /etc/puppetlabs/code/environments/DAE_14880/modules
/internal/platform/profile/manifests/network.pp, line: 52) on node vz-srv110235
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Maybe it's best to initialize `family` as empty array additionally. That worked fine for me.

**Comment by benibr** [comment]
@alvagante is there a reason why `family` could not be initialized as empty array? If not I'd suggest that.

**Comment by alvagante** [comment]
@benibr updated pr with an empty array

**Comment by benibr** [comment]
Works for me :-) Thanks for implementing

**Comment by alvagante** [comment]
merged
