### ISSUE TITLE
network::mroute on CentOS 8 not applied until manual reload

### ISSUE THREAD

**Issue by olifre** [example42/puppet-network#326]
## Expected Behavior 
Defining a:resource:
```
network::mroute { 'eth0':
  routes  => $someroutes,
}
```
should be applied at runtime / after the Puppet run. 

## Actual Behavior
`/etc/sysconfig/network-scripts/route-eth0` contains the correct configuration, but it is not applied (i.e. does not show up in `ip route`). 
Manually running:
```
nmcli device reapply eth0
```
applies the routes. 

## Steps to Reproduce the Problem
  1. Define a resource as above on CentOS 8. 
  1. Don't touch any other restart-worthy network settings. 
  1. Observe in `ip route` that the rules are not applied. 

## Analysis

`network::mroute` currently uses `$config_file_notify`, which on RedHat 8 expands to `nmcli connection reload`. This does not reload routes. 

The `reload_command` from `network::interface`, which expands to `nmcli device reapply <interface>` on CentOS 8, works well.

**Comment by olifre** [comment]
Pinging @pseiler who has contributed the most correct and complete RHEL 8 support code to this module.

**Comment by olifre** [comment]
Further testing revealed that on CentOS 8, indeed both commands are needed:
```
nmcli connection reload
nmcli device reapply <interface>
```

**Comment by pseiler** [comment]
@olifre: I try to write a patch that fixes the issue next week. I already had a look at this. Putting the exec resource _real_reload_command_ into params.pp and also trigger it should be working. The one thing I do not have a idea how to order the two exec resources. First _trigger config_file_notify_  and then trigger _real_reload_command_.

**Comment by olifre** [comment]
@pseiler Thanks!
For the ordering, would this work? 
```
Exec[$config_file_notify] -> Exec[$real_reload_command]
```
I think that if this appears at any point in the catalogue (which could be inside `network::mroute` close to the `config_file_notify` resource) the order should be ensured.

**Comment by olifre** [comment]
Hi @pseiler ,
just checking in to ask if you had time to look at this? 
Thanks and happy new year! :smile:

**Comment by pseiler** [comment]
Hi @olifre I'm sorry that I haven't messaged you yet.
I'll try to fix this issue the next week. I'm pretty busy with work at the moment.

**Comment by alvagante** [comment]
This should be fixed here: https://github.com/example42/puppet-network/pull/338

**Comment by olifre** [comment]
> This should be fixed here: #338

Can you elaborate how this should fix the issue with the `network::mroute` resource? 
That resource does not use the `$real_reload_command` defined in the `interface` resource. 

The issue described here is about adding a `network::mroute` resource for an already configured interface. As-is, that resource will only trigger `$::network::manage_config_file_notify`, which resolves to `Exec[${service_restart_exec}]` which in turn resolves to `Exec[$::network::params::service_restart_exec]`  which does `nmcli connection reload` on CentOS 8 as described in the original issue report. Notably, this is missing `nmcli device reapply eth0`, and none of that code is touched in the linked commit, so this unrelated issue is not resolved.

**Comment by alvagante** [comment]
@olifre oops you're right, looked at this too quickly. Please check if #339 solves this issue

**Comment by olifre** [comment]
@alvagante Many thanks, both for reopening and for the patch! :+1: 
I'll give it a go latest beginning of next week, this week is quite packed (and testing network changes is always a bit finicky ;-) ).

**Comment by olifre** [comment]
I'm sorry it took me that long, but I tested it just now, in a completely fresh install, first done without any `network::mroute`` resource, then adding one to the catalogue. 
It applied brilliantly, so the PR indeed fixes the issue :+1: . Thanks again!

**Comment by pseiler** [comment]
Sorry for not helping in this case. I was pretty busy and didn't find time for it. Thank you very much!

**Comment by olifre** [comment]
@pseiler No problem, I know how real life and other work can interfere all too well — luckily, #326 solves this issue well :-).
