### ISSUE TITLE
New release of puppet-network?

### ISSUE THREAD

**Issue by toddhpoole** [example42/puppet-network#329]
Hi @alvagante, @andres-moya,

I see you've [merged](https://github.com/example42/puppet-network/commit/a7bb0cbc89be07e723f0e767945c44d5da5cb180) [in](https://github.com/example42/puppet-network/commit/b34d44d7818140d724333dfa00688fc46f6dae1a) [several](https://github.com/example42/puppet-network/commit/72fe9e995088aaffff1f73046045518f2439c09b) [useful](https://github.com/example42/puppet-network/commit/55719d1d97996d20cfd236b1526bcda39cf20086) [fixes](https://github.com/example42/puppet-network/commit/d630259365367cbf13a7d508e7a92ab0668464f9) for RedHat-, CentOS-, and Fedora-based systems over the past year.

Any indication on when you'll be pushing out a new release? We'd love to use some of these new features and 3.5.3 is almost a year old.

**Comment by alvagante** [comment]
Just released 3.60 here and on the forge. 
https://forge.puppet.com/modules/example42/network/3.6.0
Thank you for the heads up.
