### ISSUE TITLE
RHEL8: Some interface options do not apply

### ISSUE THREAD

**Issue by srhuston** [example42/puppet-network#337]
## Expected Behavior 

1. Make change to DNS, DOMAIN, or RES_OPTIONS
2. Puppet applies change to files and restarts interface, reflecting change in /etc/resolv.conf

## Actual Behavior

1. Make change to options as above
2. Puppet applies change to files, restarts interface, but does not first tell NetworkManager to reload the config

## Steps to Reproduce the Problem

  1. Make change to DNS, DOMAIN, or options_extra_redhat -> RES_OPTIONS
  2. Puppet only runs 'nmcli device reapply ${interface}' but not 'nmcli con reload' first to reload configuation

Module version 3.6.0

Tested the below patch and it does the right thing (reloading the configuration and then reapplying the interface change).  I don't see any downside to the extra command.

[patch.txt](https://github.com/example42/puppet-network/files/6030351/patch.txt)

**Comment by alvagante** [comment]
Can you submit a merge request with the patch, please? In this way your name will remain in the commits history.

**Comment by srhuston** [comment]
Ah, now you're testing the limits of my git/github abilities! :D 

I'll see if I can do that later today.

**Comment by srhuston** [comment]
My noobness is showing.  #338 submitted but I don't think I linked it here right (tried to do it in the title)

**Comment by alvagante** [comment]
@srhuston actually it was linked ;-) ty!
