### ISSUE TITLE
Feature Request: Infiniband IPoIB CONNECTED_MODE support

### ISSUE THREAD

**Issue by careypa** [example42/puppet-network#34]
This is a feature request for more Infiniband support in your network module.  

We have started using your network module, and one of our RedHat interfaces that we use requires
an additional interface parameter CONNECTED_MODE: 
"""If IPoIB connected mode is enabled, it uses a large MTU for connected mode
   messages and a small MTU for datagram (in particular, multicast) messages,
   and relies on path MTU discovery to adjust MTU appropriately""", which is a decent definition from
http://git.openfabrics.org/pub/scm/~deanl/docs/release_notes/ipoib_release_notes.txt
(num 2) known issues num. 6.  

I'll be adding this parameter to manifests/interface.pp and templates/interface/*.erb within the next
few days.  Would you like me to send a patch file upstream to you?

Thank you.

**Comment by alvagante** [comment]
Closing this very old issue.
Please submit  a PR if you want this in.
Also note that with this https://github.com/example42/puppet-network/pull/85 there's the possibility to provide a custom hash of parameters to be used in a custom template.
