### ISSUE TITLE
Allow substring hostname

### ISSUE THREAD

**Issue by yosnoop** [example42/puppet-network#342]
## Expected Behavior 
Able to change the host name from 'aaabbbccc' to 'aaabbb'.

## Actual Behavior
The module does not change the host name.

## Steps to Reproduce the Problem

  1. configure the host name 'aaabbbccc'
  2. run the module with "hostname" of 'aaabbb' on the host

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.8.2003",
    major => "7",
    minor => "8",
  },

  2. Version of Puppet and of the module
  Puppet: 5.5.1
  Module: 3.3.10

  3. The relevant Puppet code and eventually Hiera data
  Currently the host name is configured with FQDN. Added the following to the hiera with expectation that it would change to host name without the domain part.
  network::hostname: "${facts.hostname}"

**Comment by alvagante** [comment]
Merged mr. Thank you
