### ISSUE TITLE
Potential Bug: hostname-RedHat.erb does not use fqdn for hostname

### ISSUE THREAD

**Issue by careypa** [example42/puppet-network#35]
Older Redhat documentation (https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Reference_Guide/ch-sysconfig.html#s2-sysconfig-network) and CentOS documentation (https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s2-sysconfig-network.html) recommend using a fqdn for hostname in /etc/sysconfig/network, which your module manages through templates/hostname-RedHat.erb.  Your module truncates the hostname variable at the first '.'.  Would you consider removing the portion that truncates after the first '.' in the RedHat erb?  Thank you.

**Comment by alvagante** [comment]
A follow up on this issue.
The fix, being backwards incompatible, will be added only at the next major version bump of the module.
The current workaround is to use a custom template for the /etc/sysconfig/network file using the ```network::hostname_file_template``` parameter.
Leaving the ticket open for future reference.

**Comment by SimonHoenscheid** [comment]
This is fixed. closed
