### ISSUE TITLE
Specifying many static routes

### ISSUE THREAD

**Issue by TomOnTime** [example42/puppet-network#37]
Is there an easy way to create many static routes?

Without Puppet, we manually edit /etc/sysconfig/network-scripts/route-bond1 to look like this:

99.99.228.0/24 dev bond1
100.100.244.0/22 via 174.136.107.1
101.101.200.0/22 via 174.136.107.1
102.102.4.0/22 via 174.136.107.1
103.103.0.0/12 via 174.136.107.1
104.104.192.0/18 via 174.136.107.1
105.105.64.0/18 via 174.136.107.1

(NOTE: the real IP addresses have been changed)

The docs don't make it clear what the hash used in a route_hash should be, nor how to specify a mix of "dev DEVICE" routes and "via IPADDRESS" routes.

Suggestions?

**Comment by alvagante** [comment]
@TomOnTime I suppose you've already managed to cope with this in other ways, anyway this https://github.com/example42/puppet-network/commit/ee319da369937d19fc5291c5e35615cdc74c96bd makes what's requested here.
