### ISSUE TITLE
RHEL / VMWare / DHCP issue with /etc/sysconfig/network-scripts/ifcfg-eth? files (check_link_down)

### ISSUE THREAD

**Issue by linuxdan** [example42/puppet-network#43]
I bring this to your attention because I found these check_link_down function definitions in the files on VMWare VM's.  I did not explicitly put them in there, but I am getting ready to use this module, so I want to be able to preserve it.

When I Googled "ifcfg-eth0 check_link_down", I found this: 
http://www.linuxforums.org/forum/red-hat-fedora-linux/180772-eth0-problems-rhel-6-a-3.html
More specifically:
http://www.linuxforums.org/forum/red-hat-fedora-linux/180772-eth0-problems-rhel-6-a-3.html#post853944

Apparently, this has beem around a LONG time : http://kb.vmware.com/kb/977
http://bugs.centos.org/bug_view_page.php?bug_id=475
https://groups.google.com/forum/#!topic/vmware.guest.linux/L_bzmNE0A78

I plan to add to the end of templates/interface/RedHat.erb surrounded by a boolean parameter.

I will make a pull request once I test.

**Comment by alvagante** [comment]
Fixed this here https://github.com/example42/puppet-network/commit/27829cabb53fb9bce44619557b07ee29e437cb5b
(Better late than never ;-)
