### ISSUE TITLE
Uninitialized constant Puppet::Pops::Loaders when using future parser in environment.conf

### ISSUE THREAD

**Issue by HT43-bqxFqB** [example42/puppet-network#56]
After updating Puppet to 3.7.5-1puppetlabs1 setting the option
```
parser = future
```
results in the following error on the validate_bool function call
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, uninitialized constant Puppet::Pops::Loaders at /etc/puppet/environments/development/modules/network/manifests/init.pp:109:3 on node xyz
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by alvagante** [comment]
This is curious, and I wonder if it's related to stdlib's validate_bool function or something in the module.
What version of stdlib and network modules are you using?
Ca you also paste the output of facter, or give some basic info about Ruby version, OS, etc.

**Comment by HT43-bqxFqB** [comment]
Puppetfile state for r10k:
mod "puppetlabs/stdlib", "4.5.1"
mod "example42/network", "3.1.20"

Facter output:
apache_version => 2.4.7-1ubuntu4.4
apt_has_updates => false
apt_update_last_success => 1428294518
architecture => amd64
augeasversion => 1.2.0
bash_version => 4.3-7ubuntu1.5
blockdevice_xvda_size => 32212254720
blockdevices => xvda
concat_basedir => /var/lib/puppet/concat
facterversion => 2.4.3
filesystems => ext2,ext3,ext4,vfat
gid => root
git_exec_path => /usr/lib/git-core
git_html_path => /usr/share/doc/git/html
git_version => 1.9.1
hardwareisa => x86_64
hardwaremodel => x86_64
has_mysql => true
hostname => ubuntu
id => root
interfaces => eth0,lo
ip6tables_version => 1.4.21
ipaddress => 10.18.XX.XX
ipaddress_eth0 => 10.18.XX.XX
ipaddress_lo => 127.0.0.1
iptables_persistent_version => 0.5.7
iptables_version => 1.4.21
is_external => false
is_pe => false
is_virtual => true
java_major_version => 7
java_patch_level => 75
java_version => 1.7.0_75
kernel => Linux
kernelmajversion => 3.13
kernelrelease => 3.13.0-48-generic
kernelversion => 3.13.0
lsbdistcodename => trusty
lsbdistdescription => Ubuntu 14.04.2 LTS
lsbdistid => Ubuntu
lsbdistrelease => 14.04
lsbmajdistrelease => 14.04
macaddress => aa:90:64:d4:17:a6
macaddress_eth0 => aa:90:64:d4:17:a6
memoryfree => 629.23 MB
memoryfree_mb => 629.23
memorysize => 989.17 MB
memorysize_mb => 989.17
mtu_eth0 => 1500
mtu_lo => 65536
mysql_version => 5.5.41-0ubuntu0.14.04.1
netmask => 255.255.0.0
netmask_eth0 => 255.255.0.0
netmask_lo => 255.0.0.0
network_eth0 => 10.18.0.0
network_lo => 127.0.0.0
openssl_version => 1.0.1f-1ubuntu2.11
operatingsystem => Ubuntu
operatingsystemmajrelease => 14.04
operatingsystemrelease => 14.04
os => {"name"=>"Ubuntu", "family"=>"Debian", "release"=>{"major"=>"14.04", "full"=>"14.04"}, "lsb"=>{"distcodename"=>"trusty", "distid"=>"Ubuntu", "distdescription"=>"Ubuntu 14.04.2 LTS", "distrelease"=>"14.04", "majdistrelease"=>"14.04"}}
osfamily => Debian
partitions => {"xvda1"=>{"uuid"=>"b76ddab5-ad0f-4de4-af2d-1c0efaa6ba61", "size"=>"60815360", "mount"=>"/", "filesystem"=>"ext4"}, "xvda2"=>{"size"=>"2"}, "xvda5"=>{"uuid"=>"69045e75-43e9-4607-b4a1-5c6cb38bf538", "size"=>"2093056", "filesystem"=>"swap"}}
path => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
physicalprocessorcount => 1
processor0 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor1 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor2 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor3 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor4 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor5 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor6 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor7 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processorcount => 8
processors => {"models"=>["Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz"], "count"=>8, "physicalcount"=>1}
ps => ps -ef
puppet_vardir => /var/lib/puppet
puppetversion => 3.7.5
root_home => /root
rubyplatform => x86_64-linux
rubysitedir => /usr/local/lib/site_ruby/1.9.1
rubyversion => 1.9.3
selinux => false
swapfree => 998.93 MB
swapfree_mb => 998.93
swapsize => 1022.00 MB
swapsize_mb => 1022.00
system_uptime => {"seconds"=>1216833, "hours"=>338, "days"=>14, "uptime"=>"14 days"}
timezone => CEST
tomcat1_version => 7.0.57-test
tomcatcount => 1
uniqueid => 120a3a33
uptime => 14 days
uptime_days => 14
uptime_hours => 338
uptime_seconds => 1216833
virtual => xenu

Same thing happens on CentOS:
apache_version => 2.2.15-39.el6.centos
architecture => x86_64
augeasversion => 1.0.0
bash_version => 4.1.2-29.el6
blockdevice_xvda_size => 42949672960
blockdevices => xvda
concat_basedir => /var/lib/puppet/concat
facterversion => 2.4.3
filesystems => ext4,iso9660
gid => root
git_exec_path => /usr/libexec/git-core
git_html_path => /usr/share/doc/git-1.7.1
git_version => 1.7.1
hardwareisa => x86_64
hardwaremodel => x86_64
has_mysql => true
hostname => centos
id => root
interfaces => eth0,lo
ip6tables_version => 1.4.7
ipaddress => 10.18.XX.XX
ipaddress_eth0 => 10.18.XX.XX
ipaddress_lo => 127.0.0.1
iptables_version => 1.4.7
is_external => false
is_pe => false
is_virtual => true
java_major_version => 7
java_patch_level => 75
java_version => 1.7.0_75
kernel => Linux
kernelmajversion => 2.6
kernelrelease => 2.6.32-504.3.3.el6.x86_64
kernelversion => 2.6.32
lsbdistcodename => Final
lsbdistdescription => CentOS release 6.6 (Final)
lsbdistid => CentOS
lsbdistrelease => 6.6
lsbmajdistrelease => 6
lsbminordistrelease => 6
lsbrelease => :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
macaddress => 92:CA:BA:36:68:3C
macaddress_eth0 => 92:CA:BA:36:68:3C
memoryfree => 657.56 MB
memoryfree_mb => 657.56
memorysize => 991.55 MB
memorysize_mb => 991.55
mtu_eth0 => 1500
mtu_lo => 65536
mysql_version => 5.1.73-3.el6_5
netmask => 255.255.0.0
netmask_eth0 => 255.255.0.0
netmask_lo => 255.0.0.0
network_eth0 => 10.18.0.0
network_lo => 127.0.0.0
openssl_version => 1.0.1e-30.el6.8
operatingsystem => CentOS
operatingsystemmajrelease => 6
operatingsystemrelease => 6.6
os => {"lsb"=>{"minordistrelease"=>"6", "distdescription"=>"CentOS release 6.6 (Final)", "distid"=>"CentOS", "majdistrelease"=>"6", "distrelease"=>"6.6", "release"=>":base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch", "distcodename"=>"Final"}, "release"=>{"minor"=>"6", "full"=>"6.6", "major"=>"6"}, "family"=>"RedHat", "name"=>"CentOS"}
osfamily => RedHat
partitions => {"xvda1"=>{"mount"=>"/boot", "uuid"=>"34ba2ad1-0350-42aa-933f-806b2a218b13", "size"=>"1024000", "filesystem"=>"ext4"}, "xvda2"=>{"size"=>"82860032", "filesystem"=>"LVM2_member"}}
path => /usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
physicalprocessorcount => 1
processor0 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor1 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor2 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor3 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor4 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor5 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor6 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processor7 => Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
processorcount => 8
processors => {"models"=>["Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz", "Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz"], "physicalcount"=>1, "count"=>8}
ps => ps -ef
puppet_vardir => /var/lib/puppet
puppetversion => 3.7.5
root_home => /root
rubyplatform => x86_64-linux
rubysitedir => /usr/lib/ruby/site_ruby/1.8
rubyversion => 1.8.7
selinux => true
selinux_config_mode => enforcing
selinux_config_policy => targeted
selinux_current_mode => enforcing
selinux_enforced => true
selinux_policyversion => 24
swapfree => 1.97 GB
swapfree_mb => 2015.94
swapsize => 1.97 GB
swapsize_mb => 2016.00
system_uptime => {"seconds"=>6647852, "uptime"=>"76 days", "hours"=>1846, "days"=>76}
timezone => CEST
tomcat1_version => 7.0.57-test
tomcatcount => 1
uniqueid => 007f0100
uptime => 76 days
uptime_days => 76
uptime_hours => 1846
uptime_seconds => 6647852
virtual => xenu

**Comment by HT43-bqxFqB** [comment]
This error doesn't occur when we use the new puppetserver with puppet4. I will close this issue, as we are planing to migrate to puppet for without the intermediate step of using the future parser.

Kind regards :)

**Comment by alvagante** [comment]
Good to hear that it works, Thank you for the update.
