### ISSUE TITLE
Unknown function default_content

### ISSUE THREAD

**Issue by sammcj** [example42/puppet-network#57]
- Puppet 3.7.5
- Debian Jessie

```
Unknown function default_content at init.pp:123
```

I *think* this might be related to #15 ?

**Comment by alvagante** [comment]
Exactly. You need the stdmod module (https://github.com/stdmod/stdmod) , just for a pair of functions:
pickx, which is very similar to stdlib pick and default_content, which  could be actually substituted by some more verbose puppet code construct.
Ok for me to accept PR that removes such dependencies and rely only on stdlib.
The quick alternative is just to add in your module path the stdmod module

**Comment by sammcj** [comment]
OK thanks @alvagante.

Great work on all your puppet modules by the way, often when we're looking for a module and we see you wrote it we end up finding it to be the best option.

Keep up the great work :)

**Comment by alvagante** [comment]
thank you!
Give a look to https://github.com/example42/puppet-tp if you want, it's the most exciting Puppet related thing I've done in the last months
