### ISSUE TITLE
ubuntu mac addr should be hwaddress not hwaddr

### ISSUE THREAD

**Issue by enemarke** [example42/puppet-network#63]
On unbuntu setting hwaddress is done by
**hwaddress class address**
and not
**hwaddr class address**

**Comment by alvagante** [comment]
Thanks for the notice, are you sure that's the correct naming for all Ubuntu versions? Is it the same on Debian?

**Comment by enemarke** [comment]
Im using ubuntu 14.04 and from the documentation on interfaces it is also true for ubuntu 12.04, 14.10 and 15.04. I dont know if this is the same on Debian.

**Comment by alvagante** [comment]
Should be fixed with the linked commit, thank you
