### ISSUE TITLE
Documentation(comments) inconsistent with code in interface.pp

### ISSUE THREAD

**Issue by neverreadsemail** [example42/puppet-network#65]
Hi,

at commit 9d4ae1486b3e4a2e412f08f4b7c37c6db25af433 in manifests/interface.pp lines 17-19 there is a comment indicating that you can use the common parameter "macaddress" in addition to the redhat specific "hwaddr" in order to specify the interfaces MAC address. however, this does not actually work and generates the error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter macaddress on Network::Interface[eth0] on node xxx.yyy.com

a cursory look at interfaces.pp does not show anywhere that the macaddress parameter is ever defined(nor anywhere is it used to set hwaddr as the comment would lead me to expect

Is this really intended to work, or is the comment just out of date/inaccurate.

thanks,
-Allie

**Comment by alvagante** [comment]
Yes there's a mismatch, the parameter to be used is hwaddr, a PR with the fix on the docs is welcomed

**Comment by neverreadsemail** [comment]
sorry it took so long, but I just submitted PR#74.

It looks like CI tests are failing, the ruby 1.9 tests are dying with a message about fog-google install failing due to fog-google requiring ruby >= 2.0. I'm not sure how this worked in the past. maybe an external dependency dropped support? In any case, I don't think it's related to my patch in any way.

**Comment by alvagante** [comment]
Yes the CI error can't be related. Ty for the pr
