### ISSUE TITLE
Default route cannot be set

### ISSUE THREAD

**Issue by mechanicalduck** [example42/puppet-network#66]
network::route does not allow setting the default route due how it is handling the gateway parameter.
The '/' of the CIDR prefix is always rendered in the if-up / if-down template, 
regardless parameter gateway was given or not, 'default/24' making it unusable for setting a default route. This applies to both Debian route templates.
https://github.com/example42/puppet-network/blob/master/templates/route_up-Debian.erb#L7
https://github.com/example42/puppet-network/blob/master/templates/route_down-Debian.erb#L7

Puppet code using this network module for setting the default route:
````
network::route { 'eth0':
    ipaddress => [ 'default', ],
    netmask   => [  ], # <- template doesn't handle empty gateway parameter, '/' is still rendered.
    gateway   => [ '10.0.0.1', ],
  }
````

/etc/network/if-up.d/z90-route-eth0
Result:
````
#!/bin/bash
#
### File managed by Puppet
#
if [ "$IFACE" = "eth0" ]; then

    ip route add default/24 via 10.0.0.1 dev eth0

fi
````
Expected:
````
#!/bin/bash
#
### File managed by Puppet
#
if [ "$IFACE" = "eth0" ]; then

    ip route add default via 10.0.0.1 dev eth0

fi
````

/etc/network/if-down.d/z90-route-eth0
Result:
````
#!/bin/bash
#
### File managed by Puppet
#
if [ "$IFACE" = "eth0" ]; then

    ip route del default/24 via 10.0.0.1 dev eth0

fi
````
Expect:
````
#!/bin/bash
#
### File managed by Puppet
#
if [ "$IFACE" = "eth0" ]; then

    ip route del default via 10.0.0.1 dev eth0

fi
````

The created scripts will silently fail when the interface is upped and downed during puppet apply.

Checking the set routes after the puppet run:
````
# ip route
````
Either no default route at all or a default route that was already set on the system will be listed, 
but not with the intended parameters.

Thank you and 
with best regards

**Comment by alvagante** [comment]
Thanks for the bug report. 
The general approach was to define the default route via the gateway parameter of the main network class, and use this define just for the other router.
We could manage the exception in the templates, but I wonder if it worth the case

**Comment by mechanicalduck** [comment]
One reason to set the default route not via gateway parameter 
would be to avoid explicitly setting all the other network interface parameters (ip address, subnet, etc) because they may have been already applied to the system (e.g. set from outside for a lxc container).

**Comment by alvagante** [comment]
You can now use the network::mroute define to add a default gw in a route file:
https://github.com/example42/puppet-network/commit/c761d96593174d61f43a51ef6d43d1e048e840e4
