### ISSUE TITLE
Error on configure interface eth0

### ISSUE THREAD

**Issue by luiszandonadi** [example42/puppet-network#76]
This error appears configuring eth0

```
err: Could not retrieve catalog from remote server: Error 400 on SERVER: Permission denied - /etc/puppet/modules/network/manifests/init.pp at /etc/puppet/environments/production/manifests/nodes/imigratec.pp:30 on node
```

```
node 'test.local' {
    network::interface { 'eth0':
      enable_dhcp => true,
    }
}
```
SO: Debian 7 x 64
Puppet: version 3.8.3 (agent and master)

Thanks!

**Comment by alvagante** [comment]
Seems like the user the puppetmaster is running with (puppet, usually) has not read access to /etc/puppet/modules/network/manifests/init.pp

Did you install the module directly from the forge?
If so what's the umask of the user running the puppet module command? It might have too strict settings.
