### ISSUE TITLE
On Debian when defining an interface ethX, only lo is defined

### ISSUE THREAD

**Issue by syss** [example42/puppet-network#77]
When I provide a single interface 'eth0' only 'lo' is defined.

      eth0:
        enable_dhcp: true
        allow_hotplug: 'eth0'
         manage_order: '08'

I have read the following: IMPORTANT NOTICE: On Debian if you use network::interface once you must provide ALL the network::interface defines for all your interfaces

from the interface manifest I have seen this for Debian OS:
            if ! defined(Network::Interface['lo']) {
                network::interface { 'lo':
                  address      => '127.0.0.1',
              method       => 'loopback',
              manage_order => '05',
            }
          }

for me it seems to be you want to handle lo if it is not defined, which works, but fails to create my interface eth0.

If I define lo explicit it works just fine:

    network::interfaces_hash:
      lo:
        address: '127.0.0.1'
        method:  'loopback'
        manage_order: '05'
      eth0:
        enable_dhcp: true
        allow_hotplug: 'eth0'
        manage_order: '08'

it seems to be, that the output file you write to /var/puppet/... is overwritten

**Comment by alvagante** [comment]
Hei, sorry for late feedback.
I've tried to reproduce this without success.
When I have in hiera this:
```
network::interfaces_hash:
  eth0:
    enable_dhcp: true
    allow_hotplug: 'eth0'
    manage_order: '08'
```

This is created in /etc/network/interfaces, as expected :
```
# Interface lo
auto lo
iface lo inet loopback

# Interface eth0
auto eth0
allow-hotplug eth0
iface eth0 inet dhcp
```

The only guess I have is that you forgot to explicit the network::interfaces_hash:
 hiera key name in your hiera files (you haven't specified it here, afterall)
