### ISSUE TITLE
Is there a way to add arbitrary configuration options for network aliases or IPv6?

### ISSUE THREAD

**Issue by stefanlasiewski** [example42/puppet-network#83]
I need to create two interfaces on my RHEL6 machine.

* One is for IPv6 traffic
* The second is a network alias

I cannot find IPv6 configuration directives in this module. Is there a way to simply add additional directives to the file without making changes to this module?

I would need directives like this:

```
IPV6ADDR="2001:0001::100"
IPV6_DEFAULTGW="2001:0001::1"
IPV6TO4INIT="yes"
```

As for a Network alias, I'd like to create a minimal file. According to the Red Hat documents at `/usr/share/doc/initscripts-*/sysconfig.txt`, a network alias should contain 'only the parts of the definition that are different in a  "alias" (or alternative) interface.' 

So in this case, I wouldn't want to use `templates/interface/RedHat.erb` as it has too many unnecessary parameters. In addition, the "ONPARENT" option does not exist in the default template, and I'm not sure how to add it without digging into the DSL & Ruby code.

Instead, I would want to have a much simpler template, like this:

```
# RHEL6 network alias template
# An alias should only have info that is different from the parent.
# See /usr/share/doc/initscripts-*/sysconfig.txt
# File Managed by Puppet
DEVICE="<%= @interface %>"
ONPARENT="yes"
<% if @manage_ipaddr -%>
IPADDR="<%= @manage_ipaddr %>"
<% end -%>
<% if @netmask -%>
NETMASK="<%= @netmask %>"
<% end -%>
<% if @broadcast -%>
BROADCAST="<%= @broadcast %>"
<% end -%>
```

**Comment by alvagante** [comment]
You can actually pass the template parameter to network::interface and place there whatever you want and use the options parameter to pass an hash of any configuration item , for example:

    options => {
      IPV6ADDR => '2001:0001::100',
    }


and then use it in your template with something like

    IPV6ADDR="<%= @options['IPV6ADDR'] %>"

**Comment by beddari** [comment]
Yes I agree that if you don't want a template with a lot of if-statements then providing your own is a solution :)

I'm however on the opposite side of that, working on some PRs expanding the generic template with even more options for IPv6 and IPsec

**Comment by beddari** [comment]
That being said, when you first wrote this @alvagante I was wondering if you'd go fully over to option hash style, writing key value pairs directly from the hash into the template. If you wanted to bring the module in that direction that would be even better in my opinion :)

**Comment by alvagante** [comment]
Closing this issue as there's a way to cope with it.
For the options_hash approach, which I and @beddari prefer, let's wait for the next major version ;-)
